spring:
  application:
    name: ninjia-eureka-service

info:
  app:
    name: ^project.name^
    version: ^project.version^
#logging:
#  level:
#    ROOT: debug
---
spring:
  profiles: ha1

server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_OTHER_HOST:localhost}:8762/eureka/
---
spring:
  profiles: ha2

server:
  port: 8762

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_OTHER_HOST:localhost}:8761/eureka/